spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/spring_redis_practice
    username: root
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.cache: trace

---

spring:
  profiles:
    default: prod
  datasource:
    url: jdbc:mysql://spring-redis-practice-database.cv4c6ysy8cvy.ap-northeast-2.rds.amazonaws.com:3306/spring_redis_practice
    username: admin
    password: password
